Description:
Given an integer numRows, return the first numRows of Pascal's triangle. In Pascal's triangle, each number is the sum of the two numbers directly above it. The first row is row 0, which is [1].



Input Parameters:

numRows (int): The number of rows of Pascal's triangle to generate.

Output:

List[List[int]]: A list of lists where each list represents a row in Pascal's triangle.



Example:

Input: numRows = 3
Output: [
  [1],
  [1, 1],
  [1, 2, 1]
]
 
Input: numRows = 1
Output: [
  [1]
]
 
Input: numRows = 5
Output: [
  [1],
  [1, 1],
  [1, 2, 1],
  [1, 3, 3, 1],
  [1, 4, 6, 4, 1]
]


Disclaimer: This Udemy coding exercise is still in development, so some advanced complexities might not be fully checked. Please use it primarily for basic code validation.



Leetcode Link : https://leetcode.com/problems/pascals-triangle/description/



In [ ]:
# WIP

8

Description:
You are given an n x n 2D matrix representing an image. Rotate the image by 90 degrees clockwise. The rotation should be done in-place, meaning you have to modify the input matrix directly without using any additional matrix for storage.



Input Parameters:

matrix (List[List[int]]): A 2D list of integers representing the matrix of size n x n.

Output:

The function should modify the matrix in-place. No need to return anything.



Example:

Input: matrix = [[5, 1, 9, 11],
                 [2, 4, 8, 10],
                 [13, 3, 6, 7],
                 [15, 14, 12, 16]]
Output: [[15, 13, 2, 5],
         [14, 3, 4, 1],
         [12, 6, 8, 9],
         [16, 7, 10, 11]]
 
 
Input: matrix = [[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]]
Output: [[7, 4, 1],
         [8, 5, 2],
         [9, 6, 3]]


Disclaimer: This Udemy coding exercise is still in development, so some advanced complexities might not be fully checked. Please use it primarily for basic code validation.



LeetCode Link: https://leetcode.com/problems/rotate-image/description/



In [33]:
# Approach 2
def rotate(matrix):
    """
    Function to rotate the matrix 90 degrees clockwise.
    :param matrix: List[List[int]] -> 2D list representing the matrix
    :return: None -> Modifies the matrix in-place
    """
    trans_matrix = []
    for j in range(len(matrix)):
        sub_matrix = []
        for i in matrix:
            # print(i[j])
            sub_matrix.append(i[j])
        trans_matrix.append(sub_matrix[::-1])
        # print(f"____{j}th_______")

    return trans_matrix

matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
print(rotate(matrix))
# Approach 1:
import numpy as np
mt = np.array(matrix)
mt1 = mt.T
mt1 = [i[::-1] for i in mt1]
print(np.array(mt1),"\n_____________\n" ,np.array(rotate(matrix)))

# Approach 3:
def rotate(matrix):
    """
    Function to rotate the matrix 90 degrees clockwise.
    :param matrix: List[List[int]] -> 2D list representing the matrix
    :return: None -> Modifies the matrix in-place
    """
    # Step 1: Transpose the matrix (swap rows and columns)
    n = len(matrix)
    for i in range(n):
        for j in range(i, n):
            # Swap matrix[i][j] and matrix[j][i]
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
 
    # Step 2: Reverse each row of the matrix
    for i in range(n):
        matrix[i].reverse()

    return matrix
  
# Example usage (can be removed)
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
rotate(matrix)


[[7, 4, 1], [8, 5, 2], [9, 6, 3]]
[[7 4 1]
 [8 5 2]
 [9 6 3]] 
_____________
 [[7 4 1]
 [8 5 2]
 [9 6 3]]


[[7, 4, 1], [8, 5, 2], [9, 6, 3]]

Description:
You are given two n x n binary matrices mat and target. Your task is to determine whether it is possible to make mat equal to target by rotating mat in 90-degree increments (clockwise). You can rotate mat by 90, 180, or 270 degrees, or leave it unchanged.



Input Parameters:

mat (List[List[int]]): A n x n binary matrix.

target (List[List[int]]): A n x n binary matrix.

Output:

bool: Return True if mat can be made equal to target by rotating it, otherwise return False.



Example:

Input: mat = [[0, 0, 0], [0, 1, 0], [1, 1, 1]], target = [[1, 1, 1], [0, 1, 0], [0, 0, 0]]
Output: True
 
Input: mat = [[0, 1], [1, 1]], target = [[1, 0], [0, 1]]
Output: False


Disclaimer: This Udemy coding exercise is still in development, so some advanced complexities might not be fully checked. Please use it primarily for basic code validation.



LeetCode Link: https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/

In [ ]:
mat = [[0, 0, 0], [0, 1, 0], [1, 1, 1]]
target = [[1, 1, 1], [0, 1, 0], [0, 3, 0]]

def can_be_rotated(mat, target):
    """
    Function to check if mat can be rotated to match target.
    :param mat: List[List[int]] -> The original matrix
    :param target: List[List[int]] -> The target matrix
    :return: bool -> True if mat can be rotated to match target, otherwise False
    """
    return mat[::-1] == target

can_be_rotated(mat, target)

# Approach 2
def rotate_90(matrix):
    """
    Function to rotate a matrix 90 degrees clockwise.
    :param matrix: List[List[int]] -> The matrix to rotate
    :return: List[List[int]] -> Rotated matrix
    """
    n = len(matrix)
    rotated = [[0] * n for _ in range(n)]
    
    for i in range(n):
        for j in range(n):
            rotated[j][n - 1 - i] = matrix[i][j]
    
    return rotated
 
def can_be_rotated(mat, target):
    """
    Function to check if mat can be rotated to match target.
    :param mat: List[List[int]] -> The original matrix
    :param target: List[List[int]] -> The target matrix
    :return: bool -> True if mat can be rotated to match target, otherwise False
    """
    for _ in range(4):
        if mat == target:
            return True
        mat = rotate_90(mat)
    return False
 
# Helper function to display the result (for debugging)
def display_result(mat, target):
    result = can_be_rotated(mat, target)
    print(result)
 
# Example usage (can be removed)
# mat = [[0, 1], [1, 0]]
# target = [[1, 0], [0, 1]]
# display_result(mat, target)  # Output should be True


False